---

- name: install build-essential
  apt: pkg=build-essential state=latest update_cache=yes cache_valid_time=3600
  tags:
    - common
    - build

- name: install git-core
  apt: pkg=git-core state=latest update_cache=yes cache_valid_time=3600
  tags:
    - common
    - git

- name: install ntp
  apt: pkg=ntp state=latest update_cache=yes cache_valid_time=3600
  tags:
    - common
    - ntp

- name: configure ntp
  template: src=etc/ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp service
  tags:
    - common
    - ntp

- name: install iptables-persistent
  apt: pkg=iptables-persistent state=latest update_cache=yes cache_valid_time=3600
  tags:
    - common
    - iptables

- name: configure iptables-persistent rules
  template: src=etc/iptables/rules.v4.j2 dest=/etc/iptables/rules.v4
  notify: reload iptables-persistent service
  tags:
    - common
    - iptables

- name: configure interfaces
  template: src=etc/network/interfaces.j2 dest=/etc/network/interfaces
  notify: restart networking service
  tags:
    - common
    - interfaces

- name: configure ssh
  template: src=etc/ssh/sshd_config.j2 dest=/etc/ssh/sshd_config
  notify: restart ssh service
  tags:
    - common
    - ssh

- name: configure sysctl
  template: src=etc/sysctl.conf.j2 dest=/etc/sysctl.conf
  notify: reload sysctl configuration
  tags:
    - common
    - sysctl

- name: secure /usr/local/bin
  file: state=directory path=/usr/local/bin mode=0711 owner=root group=root recurse=yes
  tags: common

- name: secure /etc
  file: state=directory path=/etc mode=0711
  tags: common

- name: secure /tmp
  file: state=directory path=/tmp mode=1777 recurse=yes
  tags: common

- name: secure /var/tmp
  file: state=directory path=/var/tmp mode=1777 recurse=yes
  tags: common
