---

- name: restart apache service
  service: name=apache2 state=restarted
  notify: warm up canvas apache site

- name: warm up canvas apache site
  shell: wget -qO- --no-check-certificate http://127.0.0.1:8080/login &> /dev/null
  ignore_errors: yes
