---

# Usage: ansible-playbook -i inventory util_initialize_rdb.yml

# ---------------------------------------------------------------------------------------------------------------------
# Localhost cloud size.
# ---------------------------------------------------------------------------------------------------------------------

- hosts: rdb_standby_master
  remote_user: root
  tasks:
    - name: start postgres service
      service: name=postgresql state=started
      when: this_size == "localhost"

# ---------------------------------------------------------------------------------------------------------------------
# Small cloud size.
# ---------------------------------------------------------------------------------------------------------------------

- hosts: rdb_standby_slave
  remote_user: root
  tasks:
    - name: stop postgres service
      service: name=postgresql state=stopped
      when: this_size == "small"

    - name: remove postgres data
      shell: rm -rf /var/lib/postgresql/9.3/main/*
      when: this_size == "small"

    - name: configure postgresql recovery
      template: src=roles/postgresql/templates/var/lib/postgresql/9.3/main/recovery.conf.j2 dest=/var/lib/postgresql/9.3/main/recovery.conf owner=postgres group=postgres mode=0600
      when: this_size == "small"

- hosts: rdb_standby_master
  remote_user: root
  tasks:
    - name: start postgres service
      service: name=postgresql state=started
      when: this_size == "small"

    - name: start postgres master backup
      sudo: yes
      sudo_user: postgres
      shell: psql -U postgres -c "select pg_start_backup('init', true);"
      when: this_size == "small"

    - name: pause
      pause: seconds=30
      when: this_size == "small"

    - name: rsync postgres data
      sudo: yes
      sudo_user: postgres
      shell: rsync -az -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" /var/lib/postgresql/9.3/main/ {{ hostvars[groups['rdb_standby_slave'][0]].ansible_eth0.ipv4.address }}:/var/lib/postgresql/9.3/main/ --exclude postmaster.pid
      when: this_size == "small"

    - name: stop postgres master backup
      sudo: yes
      sudo_user: postgres
      shell: psql -U postgres -c "select pg_stop_backup();"
      when: this_size == "small"

- hosts: rdb_standby_slave
  remote_user: root
  tasks:
    - name: start postgres service
      service: name=postgresql state=started
      when: this_size == "small"
